Fix windows vtkSlicerDicomRtImportExportModuleLogicPythonD build errors
This commit fixes windows build error and redefined warnings introduced
by the Slicer commit r24586 (ENH: Update DMCTK to use version
DCMTK-3.6.1_20150924)

Related Slicer commits:
* r24136 (STYLE: Update CTK to fix warning related to wrapping of CTKDICOM module)
* r23955 (COMP: Workaround to fix HAVE_STAT redefined warning in SlicerDICOMExportDialog)
* r23952 (COMP: Workaround to fix HAVE_STAT redefined warning in qSlicerCoreApplication)

Error and warning fixed by the commit:

vtkSlicerDicomRtImportExportModuleLogicPythonD - 35 error(s), 10 warning(s)

2>C:\S-bld\DCMTK-build\config\include\dcmtk/config/osconfig.h(175) : warning C4005: 'HAVE_FTIME' : macro redefinition
2>        c:\s-bld\python-install\include\pyconfig.h(582) : see previous definition of 'HAVE_FTIME'
2>C:\S-bld\DCMTK-build\config\include\dcmtk/config/osconfig.h(217) : warning C4005: 'HAVE_GETPID' : macro redefinition
2>        c:\s-bld\python-install\include\pyconfig.h(593) : see previous definition of 'HAVE_GETPID'
2>C:\S-bld\DCMTK-build\config\include\dcmtk/config/osconfig.h(274) : warning C4005: 'HAVE_IO_H' : macro redefinition
2>        c:\s-bld\python-install\include\pyconfig.h(58) : see previous definition of 'HAVE_IO_H'
2>C:\S-bld\DCMTK-build\config\include\dcmtk/config/osconfig.h(570) : warning C4005: 'HAVE_STAT' : macro redefinition
2>        c:\s-bld\python-install\include\pyport.h(374) : see previous definition of 'HAVE_STAT'
2>C:\S-bld\DCMTK-build\config\include\dcmtk/config/osconfig.h(622) : warning C4005: 'HAVE_STRERROR' : macro redefinition
2>        c:\s-bld\python-install\include\pyconfig.h(64) : see previous definition of 'HAVE_STRERROR'
2>C:\S-bld\DCMTK-build\config\include\dcmtk/config/osconfig.h(718) : warning C4005: 'HAVE_SYS_UTIME_H' : macro redefinition
2>        c:\s-bld\python-install\include\pyconfig.h(59) : see previous definition of 'HAVE_SYS_UTIME_H'
2>C:\S-bld\DCMTK-build\config\include\dcmtk/config/osconfig.h(727) : warning C4005: 'HAVE_TEMPNAM' : macro redefinition
2>        c:\s-bld\python-install\include\pyconfig.h(60) : see previous definition of 'HAVE_TEMPNAM'
2>C:\S-bld\DCMTK-build\config\include\dcmtk/config/osconfig.h(736) : warning C4005: 'HAVE_TMPNAM' : macro redefinition
2>        c:\s-bld\python-install\include\pyconfig.h(62) : see previous definition of 'HAVE_TMPNAM'
2>C:\S-bld\DCMTK-build\config\include\dcmtk/config/osconfig.h(974) : warning C4005: 'HAVE_LONG_LONG' : macro redefinition
2>        c:\s-bld\python-install\include\pyconfig.h(304) : see previous definition of 'HAVE_LONG_LONG'
2>C:\S-bld\DCMTK\ofstd\include\dcmtk/ofstd/oftypes.h(111) : error C2146: syntax error : missing ';' before identifier 'Sint64'
2>C:\S-bld\DCMTK\ofstd\include\dcmtk/ofstd/oftypes.h(111) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>C:\S-bld\DCMTK\ofstd\include\dcmtk/ofstd/oftypes.h(111) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int